### ISSUE TITLE
Everblush colorscheme configs?

### ISSUE THREAD

**Issue by eghere** [Syndrizzle/hotfiles#10]
I love your rice, especially the original colorscheme you used in an [older reddit post](https://i.redd.it/3nm9jylg8k191.png). Do you still have configs that would have the Everblush color scheme over Catpuccin, and if not, how would I go about applying the colorscheme myself?

**Comment by N3k0Ch4n** [comment]
You can actually go through any timeline/history of any repo. Just click at the text 'Commit' and search which timeline that used everblushed colorscheme.
![idk](https://user-images.githubusercontent.com/95261992/175504102-721634dd-b4cc-464c-9707-35bed8e7633e.png)

**Comment by Syndrizzle** [comment]
Sorry, but I don't have the everblush ones now, since i resetted the commit history after switching to everblush because some things were not working atm
