### ISSUE TITLE
Unable to get dunst notifications to appear in Control Center

### ISSUE THREAD

**Issue by N0tallion6** [Syndrizzle/hotfiles#11]
Hi,

For some reason I just cannot get notifications to appear in the Control Center widget.

I definitely have Dunst & eww installed. I've checked the `notifications.txt` file located in `~/.cache/dunst`. It exists, but always seems empty, which implies that notifications are somehow not getting written to it. 

I checked that I appended the 3 lines for the `logger.zsh` script to my dunstrc, even tried replacing the whole file with the dunst config that comes with this repo, but neither of those appear to fix it.

I'm relatively new to using Eww, so it's possible I've missed something obvious - Am I missing something?

If it helps at all, I'm initializing Eww at runtime using `eww daemon --config ~/.config/eww/Control-Center`. I'm fairly certain that's correct though...

Also, when attempting to run `./logger.zsh subscribe` in the `Control-Center` directory prints the following in my terminal:
`(box :class "control-center-empty-box" :height 590 :orientation "vertical" :space-evenly false (image :class "control-center-empty-banner" :valign "end" :vexpand true :path "assets/empty-notification.svg" :image-width 200 :image-height 200) (label :vexpand true :valign "start" :wrap true :class "control-center-empty-label" :text "To fake it is to stand guard over emptiness  -Arthur Herzog"))`

**Comment by Syndrizzle** [comment]
check the 3 things and give me their outputs
1. Your dunst version?
`dunst --version`

2. Check if the location of logger.zsh specified in `dunstrc` is correct
3. Check if logger.zsh is executable.

Why? because the thing you are getting when you run `./logger.zsh subscribe` indicates that your dunst is not responding to notifications, that's why there is just the empty one.

**Comment by N0tallion6** [comment]
Thanks for the quick reply!

My `dunst --version` appears to be 1.8.1. (2022-03-02) Seems to be the latest from the Manjaro repository.

I checked the location of the logger.zsh against what was written in my dunstrc. They are both identical. (located in `~/.config/eww/Control-Center/scripts`) also tried changing the path to the logger to absolute ("`/home/me/`" instead of "`~/`") to see if that would help, but no dice. 

According to my `ls -al` output, the file is executable, along with every other script file in there.

**Comment by Syndrizzle** [comment]
This is weird..

**Comment by N0tallion6** [comment]
Are there any other dependencies that the widgets rely on? I figured that I'd only need Dunst & Eww to make the Control Center widgets work and only installed those. 

Also, just to check, the widgets should work regardless of which Window Manager you're running them on, correct? I'm using BSPWM right now.

**Comment by Syndrizzle** [comment]
Yeah you need `moreutils`, `recode` and `zsh` to make them work on arch

**Comment by N0tallion6** [comment]
Ah... that's what was missing...
Somehow I missed those when installing the dependencies - my mistake! 

Thanks for your help.

**Comment by Syndrizzle** [comment]
No problem!
