### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by Nota30** [Syndrizzle/hotfiles#14]
Some of the dependencies are not found.
can be installed through `pamac install uthash`
I think there are more.
![image](https://user-images.githubusercontent.com/60175653/176444033-d8ea5950-604f-43e4-b7ce-25f4b33e70e7.png)

**Comment by Nota30** [comment]
also `libconfig` too

**Comment by Nota30** [comment]
picom

**Comment by atxr** [comment]
I reopen this issue because I found during the picom installation that the dependency `a2x` was also missing for me during the build
Simply fixed with a 
`sudo pacman -S asciidoc`

**Comment by Syndrizzle** [comment]
Alright, thank you!
