### ISSUE TITLE
Error in Installation tutorial 

### ISSUE THREAD

**Issue by NateyBoyDM** [Syndrizzle/hotfiles#2]
Hello! I am installing the dotfiles currently and noticed an error in the main package install section of the Arch Linux install portion of the guide. The command is 
`paru -S xdg-user-dirs git slim dunst tint2 jgmenu rofi alacritty nitrogen sxhkd i3lock-color picom-jonaburg-fix lua starship fish cava gtk brightnessctl zsh playerctl pipewire pipewire-pulse thunar
papirus-icon-theme curl jq libappindicator-gtk3 org.freedesktop.secrets light wireless_tools maim gpick mate-polkit yaru-sound-theme xdg-desktop-portal-gtk xdg-desktop-portal mpv jgmenu lxappearance xfce-power-manager xfce4-settings xprintidle vdirsyncer khal moreutils fortune-mod wmctrl bc unzip bluez bluez-utils imagemagick parcellite xclip pamixer pavucontrol rofimoji rofi-greenclip `
and the error in question is the xfce-power-manager package. At least for me, when I try to do this with the yay package manager, I have to use 
`xfce4-power-manager`
 for this to work. I could be completely wrong when saying this, but I just thought I'd let you know in case anyone else has this error.

**Comment by Syndrizzle** [comment]
Thank you for this! I have fixed it, I guess I forgot to put a 4 after xfce :)
