### ISSUE TITLE
Meson command needs more dependencies

### ISSUE THREAD

**Issue by CeriOwl** [Syndrizzle/hotfiles#24]
When I try to use the meson command in the step 3, gives me a problem with two dependencies, you need to install uthash with `sudo pacman -S uthash` and asciidoc with `sudo pacman -S asciidoc`. If you havent It gives you this two errors:
`man/meson.build:3:1: ERROR: Program 'uthash' not found or not executable`
`man/meson.build:3:1: ERROR: Program 'a2x' not found or not executable`

**Comment by Syndrizzle** [comment]
Tysm for this! I guess uthash was missing from the readme, added!
