### ISSUE TITLE
How to make it work on a 1366x768 laptop screen.

### ISSUE THREAD

**Issue by TheCoolGDev** [Syndrizzle/hotfiles#27]
everything seems larged out and the eww widget and polybar goes out of my screen ;-;..
what files should i edit to fix this?

**Comment by Syndrizzle** [comment]
Almost everything, and sorry I can't help you with this since I don't have any 1366x768 monitor 🙁
Although files that you need to edit are in `eww`, `polybar`, `glava`, `tint2` and `rofi` folder
