### ISSUE TITLE
Use dccsillag’s fork of picom 

### ISSUE THREAD

**Issue by Forgotten-Email** [Syndrizzle/hotfiles#28]
I suggest using dccsillag’s fork because compared to pijulius’ fork, it’s kept up to date (not behind any commits to the main branch as of now), is less buggy and supports the same animations. Plus, it’s available in the AUR under the picom-animations-git which will make the install process easier.

**Comment by Syndrizzle** [comment]
I didn't notice any core difference between the performance of dccsillag's fork and pijulius fork. Also dccsillag's fork doesn't include some of the closing animations, so nope
