### ISSUE TITLE
very large polybar and some functions doesnt work

### ISSUE THREAD

**Issue by AcoXR5** [Syndrizzle/hotfiles#29]
Hello,
Polybar is very large i dont how to change tottaly newbie with this
Some functions doesnt work like jgmenu, polybar buttons etc..
my monitor is 1920x1080
Its very nice rice 
Sorry for bad english

**Comment by Syndrizzle** [comment]
For polybar you can try to edit the `~/.config/polybar/config.ini` file to change the font and bar size.
for jgmenu you need to compile `xqp`, make sure you've done that, and also u need to install `xdo`.
Polybar buttons should work, i think you need to install just eww widgets for them.
