### ISSUE TITLE
Question about the screen widgets

### ISSUE THREAD

**Issue by midnightcat7** [Syndrizzle/hotfiles#31]
I want to ask how did you make those widgets on the middle of the screen like the time on the top right and cpu on the bottom left, etc.? I've tried creating them with eww but it get over the windows, also I didn't find them on the code file. thank you

**Comment by Syndrizzle** [comment]
It is not made using eww, it is conky :)

**Comment by midnightcat7** [comment]
I'll try it, thank you :)
