### ISSUE TITLE
key bind and mouse right-click

### ISSUE THREAD

**Issue by MimiValsi** [Syndrizzle/hotfiles#32]
Hey,

First thing first, your hotfiles are dop!
So installed everything with paru etc, got my API weather working smoothly, there still some minor thing to process but get there.
In the meanwhile, still can't figure why my mouse right-click doesn't work and can't find the file which process that.

For the key binds, on my keyboard, I don't have Super key cap, I just use Window key. I know that in Xorg, Win key is $mod4 but in sxhkd, it doesn't seems to work, I even try the other mods. Beside changing in sxhkd file, is there anything else to do to activate the modification?

Oh and is there any way to resize some windows? like kitty?

Thx on advance :)

**Comment by MimiValsi** [comment]
The right-click on desktop at least doesn't work. The one universal didn't try yet. What's weird is that I can drag the windows with window(Super) key but not resize nor open others commands. Will try more tonight after work.

**Comment by MimiValsi** [comment]
ok so I changed from mod4 to mod1 to alt etc nothing. Can confirm that using super+mouse right click on terminal (exemple), I can resize the window. With super + mouse left click I can drag windows. And still can't use super+Return to open a terminal or super+q to kill it. Weird

**Comment by MimiValsi** [comment]
Well, i think my problem is gone. I try to reinstall sxhkd, apparently it wasn't even installed lol
Now everything works correctly.
Thank you anyway :)

**Comment by Syndrizzle** [comment]
Amazing!
