### ISSUE TITLE
Will there be a openbox edition 

### ISSUE THREAD

**Issue by Partha2003** [Syndrizzle/hotfiles#34]
I was wondering if you will ever consider a openbox edition.

**Comment by Syndrizzle** [comment]
I don't think so, because currently FVWM does everything that openbox can do, infact its even more extensible, so I'll never have to use openbox :) but I will try, thanks for the idea!

**Comment by Partha2003** [comment]
Ah well even if you don't make the entire thing from scratch again for openbox, i was wondering if you could make a control center applet maybe which might work on openbox, i absolutely love the one you have made and i hoping to see the same possible in openbox. A humble request from my end, if you have a moment for this endeavour. 🙂

**Comment by Syndrizzle** [comment]
You can use the control center on openbox as well, since these are just eww widgets.

**Comment by Partha2003** [comment]
> You can use the control center on openbox as well, since these are just eww widgets.

Actually properly installed eww and copied the config files now but i do not know how to exactly launch it everytime. 😅

**Comment by Partha2003** [comment]
I found the launch script but the widget itself appears broken.

**Comment by Partha2003** [comment]
Fyi there was no .config/eww, i manually copied the files and i confirmed use/bin/eww exists. Is there a different config location present?

**Comment by Syndrizzle** [comment]
Nope, it's just .config/eww, can u share the screenshot of the broken widget?

**Comment by Partha2003** [comment]
![2022-08-13-193925_1920x1080_scrot](https://user-images.githubusercontent.com/96782754/184497959-c9f747f1-330a-450f-a254-394802855884.png)
Missing icons and functionalities
This might sound dumb but i am launching it like this
/home/partha/.config/eww/System-Menu/launch

**Comment by Syndrizzle** [comment]
* For bluetooth you obviously need bluetooth installed
* For the wifi connection arrow, you need the networkmanager_dmenu package
* For changing the geometry, you can change the width and height of the widget in `defwindow`
* You are missing programs, `rfkill` for airplane mode, `redshift` for night light and `dunst` for do not disturb

**Comment by Partha2003** [comment]
> * For bluetooth you obviously need bluetooth installed
> * For the wifi connection arrow, you need the networkmanager_dmenu package
> * For changing the geometry, you can change the width and height of the widget in `defwindow`
> * You are missing programs, `rfkill` for airplane mode, `redshift` for night light and `dunst` for do not disturb

Ah well then I'll apply fixes and get back to you.

**Comment by Partha2003** [comment]
Again on a unrelated side note, may i request something that you might be able to help me with in openbox? I am really grateful for the help you have provided, but there's one thing i am missing which i haven't been able to obtain, I don't have a disk and drive manager applet, i was hoping if you could help me with that.

**Comment by Syndrizzle** [comment]
disk drive manager applet? wdym?

**Comment by Partha2003** [comment]
> disk drive manager applet? wdym?

Basically this for linux
![Screenshot_2022-08-15-17-27-11-99_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/96782754/184631151-a43f04e9-2b42-40eb-985b-41fce79b1022.jpg)

**Comment by Syndrizzle** [comment]
Ah no there isn't one, sorry :/

**Comment by mrlinuxdude** [comment]
hey @Partha2003  i love your bar. where do i get it from

**Comment by Partha2003** [comment]
> hey @Partha2003 i love your bar. where do i get it from

Ah apologies for late reply i am using tint2 for that and here are the dotfiles incase  you want to check it out 
https://github.com/owl4ce/dotfiles

**Comment by Partha2003** [comment]
> There exists one for gnome though https://extensions.gnome.org/extension/7/removable-drive-menu/

Did'nt really work for me unfortunately.

**Comment by Syndrizzle** [comment]
Oh, I am not aware of anything else, sorry.
