### ISSUE TITLE
Amazing dots. Truly amazing. I love you

### ISSUE THREAD

**Issue by mrlinuxdude** [Syndrizzle/hotfiles#35]
I haven't tried bspwn yet but WOW I love spotify stuff. i always used conky and cover art damn this is amazing. I can't wait to try this out on my system Thank you so much. any plans for xfce edition. If not will the spotify music thing work on xfce? just wondering because i seen somebody ask about openbox.

**Comment by Syndrizzle** [comment]
Yeah it will :)

**Comment by mrlinuxdude** [comment]
How would i go about installing everything to xfce and getting it to work. Thanks. Do i still need to install bspwm stuff

**Comment by mrlinuxdude** [comment]
I installed everything but bspwm and the the bspwm rounded corners git. I'm not sure how to launch music player popup xfce. i tried launching the system Menu Popup and got this

`/home/linux/.local/bin/eww: line 1: version: command not found
/home/linux/.local/bin/eww: line 2: oid: command not found
size: '336766984': No such file
`

**Comment by mrlinuxdude** [comment]
I got it working little bit. I didn't know needed polybar to run with the music player. There's some some need to fix. if you can help. i'll send screenshots

**Comment by mrlinuxdude** [comment]
<a href="https://www.imagebam.com/view/MEC9535" target="_blank"><img src="https://thumbs4.imagebam.com/2f/83/bf/MEC9535_t.png" alt="xfce-Syndrizzle-hotfiles.png"/></a>

The battery i'm not to worried about. How do i fix the polybar corners and its little too big there's some black corners cuttoff on polybar. Also the upspeed and downspeed network. Also what icons where you using? there was no icon package. What was the dock think at the bottom on your screenshot where you using tint2 also.  Thanks

**Comment by Syndrizzle** [comment]
You don't need polybar for this, you just launch it using eww. The bottom thing is plank dock

**Comment by mrlinuxdude** [comment]
The Music Player wouldn't launch without polybar. For me. How can i fix the polybar? Also what icons are you using no mention.

**Comment by Syndrizzle** [comment]
I am using papirus-icon-theme, there is no upload/download indicator in polybar that is actually for gamemode, which you need to have installed, to open player without polybar u can use `eww open player`
