### ISSUE TITLE
Little BSPWM issue

### ISSUE THREAD

**Issue by MimiValsi** [Syndrizzle/hotfiles#36]
Heyo,

Still using your BSPWM with some personal tweaks, and one things that bothers me is when I click on the time @ the middle of the bar or the system menu, the windows pop up and everything behind goes dark.
There's some rare times that doesn't thought.

Got any idea what can make that?

thx for your time

**Comment by Syndrizzle** [comment]
Are you using a compositor? That shouldn't happen after using one, basically we spawn a transparent window behind that control center, that transparent window acts as a wrapper for closing the widget when u click outside of it, so if you are clicking outside the widget you are actually clicking that transparent window.
If you are using a compositor and the issue still persists, you might just want to remove that window by editing the polybar modules.ini file in `~/.config/polybar/modules.ini`, and removing background-closer. Also after that you will only be able to close the widget again after clicking on the time.

**Comment by MimiValsi** [comment]
I see better now. Yes, I'm still using picom compositor. @ the moment everything ok but if the issue comes back I'll remove it.
Thx for the help mate :)

**Comment by Syndrizzle** [comment]
No problem :)

**Comment by Corrupter-rot** [comment]
@MimiValsi @Syndrizzle I did have the same problem. The thing I found was when I try locking and unlocking the system picom process was killed for some reason and never restarted. That's why there are black background popping when a popup is open.

**Comment by Syndrizzle** [comment]
Are you still having this issue? Or did you solve it

**Comment by Corrupter-rot** [comment]
After a system update i don't see the problem anymore.

**Comment by Syndrizzle** [comment]
Okay
