### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by TalinTheDev** [Syndrizzle/hotfiles#37]
I just reinstalled Arch and found this so decided to try it. After installing arch and getting gnome to access it all, I followed every step here and then restarted. It isn't working. There is no difference and fvwm doesn't show up as a display (like gnome or plasma) in the login menu. I did switch from Gdm to slim though. 

Thanks for your help.

**Comment by Syndrizzle** [comment]
Please try to install it without gnome :/

**Comment by TalinTheDev** [comment]
@Syndrizzle After messing around, I managed to get it to kind of work but because my screen is the wrong size I don't think it will work right. Thanks anyways. It looks great!

**Comment by TalinTheDev** [comment]
So since I can't find a better-looking rice, and I like BSPWM better than the new one, I decided to try it. My screen size is 1366x768. Could you help me with the screen sizing. Thanks.

**Comment by Syndrizzle** [comment]
You gotta edit almost every file :pensive:

**Comment by TalinTheDev** [comment]
@Syndrizzle Like every every file or just the eww ones? Do you think anyone has a list of things to change or even just files to change so I don't have to go through every file and see if there is anything to change? Or maybe just a list of options to change so at least I know what I'm looking for when I start.

**Comment by TalinTheDev** [comment]
I'm going to start a new issue with a different title.
