### ISSUE TITLE
No notifications in other WMs

### ISSUE THREAD

**Issue by Sveske-Juice** [Syndrizzle/hotfiles#38]
There are no notifications in the notification window. If i manually run `scripts/logger.py subscribe` I only see the quote. 

Dunst works fine and displays messages.

**Comment by Sveske-Juice** [comment]
Found out the issue to be that the `logger.py` scripts needs to be initialized. So i have to run this line on startup:
`$XDG_CONFIG_HOME/eww/scripts/logger.py init` on startup, which in i3wm looks like this:
`exec --no-startup-id $XDG_CONFIG_HOME/eww/scripts/logger.py init`

**Comment by Syndrizzle** [comment]
Yes
