### ISSUE TITLE
it looks amazing, but the locale is broken (fvwm version)

### ISSUE THREAD

**Issue by wortermeylon** [Syndrizzle/hotfiles#39]
Hi 
I've just installed your dotfiles (i love them btw :smile: ) but now I'm having trouble with locale, and some applications eg gnome-terminal won't start. It's giving me these error messages:
`Locale not supported by C library.`  and
`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)` (this happens when I try to locale-gen with en_GB.UTF-8)
in /etc/locale.conf+.gen my locale is en_GB.UTF-8, so not sure why this happens.
Does the fvwm hotfiles change locale in any way? How can I fix this and stop my system from being stuck on en_US?
Thank you

**Comment by Syndrizzle** [comment]
That is not an fvwm issue, instead your locale is just not being recognized.
I think if you run the below commands, it might fix it for you:
```bash
sudo su -
echo "LC_ALL=en_GB.UTF-8" >> /etc/environment
echo "en_GB.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_GB.UTF-8" > /etc/locale.conf
locale-gen en_GB.UTF-8
```
Try it, if it doesn't work then try en_US.UTF-8, most programs support it :smile:

**Comment by wortermeylon** [comment]
Hi
Thanks - that, along with generating the en_US locale again, seems to have fixed the problem.
:)

**Comment by Syndrizzle** [comment]
Great!
