### ISSUE TITLE
not sure how to describe this

### ISSUE THREAD

**Issue by DarwinUang** [Syndrizzle/hotfiles#4]
so, i got everything working properly (except slim, i had to use lightdm because slim was missing a “slim.auth” and refused to run without one)

anyways, i log in to find… nothing.
![image](https://user-images.githubusercontent.com/61612754/171972195-52f3109c-9ad6-4cd0-b90d-a30d87645718.jpg)

**Comment by Syndrizzle** [comment]
So if you are relying on lightdm, does it lists you the worm as a session?

**Comment by DarwinUang** [comment]
@Syndrizzle yes

**Comment by Syndrizzle** [comment]
> @Syndrizzle yes

Can you please check if the configuration files are there? In `.config` folder?

**Comment by DarwinUang** [comment]
> > @Syndrizzle yes
> 
> Can you please check if the configuration files are there? In `.config` folder?

![image](https://user-images.githubusercontent.com/61612754/171987530-f223d347-7094-4a6c-bfbd-00ce7a65386b.jpg)

that looks right

**Comment by Syndrizzle** [comment]
Did you install worm using AUR? Also I will try to install this on a virtual machine to see if there is anything thats causing it to not show up.

**Comment by DarwinUang** [comment]
> Did you install worm using AUR? Also I will try to install this on a virtual machine to see if there is anything thats causing it to not show up.

yep, i built it with makepkg once, and used yay the second time.

**Comment by Syndrizzle** [comment]
did you copy my `.xinitrc`? If yes then can you install `xorg-xinit` and run `startx` from the tty?

**Comment by DarwinUang** [comment]
> did you copy my `.xinitrc`?

if i didnt (which is unlikely but still possible), i did now.

> can you install `xorg-xinit`

yes

> run `startx`

no (i got the exact same result (black wallpaper, what im assuming is the Catppuccin cursor (which i can move), and nothing else)

here are the commands i ran in the tty(2):

yay -S xorg-xinit ; cd /tmp ; git clone https://github.com/Syndrizzle/hotfiles ; cd hotfiles ; cp .gtkrc-2.0 .vimrc .xinitrc ~/ ; startx

**Comment by Syndrizzle** [comment]
You had to do `cp .xinitrc ~/.xinitrc` not `~/startx`

**Comment by DarwinUang** [comment]
> Oh, well I just found out some error in the readme for arch install instructions. So can u try to copy paste the below command for all the packages and then reboot?
> 
> ```
> yay -S xorg xdg-user-dirs git slim dunst tint2 jgmenu rofi alacritty nitrogen sxhkd i3lock-color picom-jonaburg-fix lua starship fish cava gtk brightnessctl zsh playerctl pipewire pipewire-pulse thunar papirus-icon-theme curl jq libappindicator-gtk3 org.freedesktop.secrets light wireless_tools maim gpick mate-polkit yaru-sound-theme xdg-desktop-portal-gtk xdg-desktop-portal mpv jgmenu lxappearance xfce4-power-manager xfce4-settings xprintidle vdirsyncer khal moreutils fortune-mod wmctrl bc unzip bluez bluez-utils imagemagick parcellite xclip pamixer pavucontrol rofimoji rofi-greenclip glibc gcc ninja nim
> ```
> 
> See if it works then

nope, didnt help at all

**Comment by Syndrizzle** [comment]
Weird....I have got no experience with bedrock, if you installed work using the AUR it was supposed to move the wormc binary as well.
Can you do `which wormc` and see if it outputs anything?

**Comment by DarwinUang** [comment]
> Weird....I have got no experience with bedrock, if you installed worm using the AUR it was supposed to move the wormc binary as well.
> Can you do `which wormc` and see if it outputs anything?

$ which wormc
/usr/bin/wormc

**Comment by Syndrizzle** [comment]
Well then, as I said I got no experience how bedrock works. But I got this from their website:
`Occasionally, software may become confused by Bedrock's environment. Most notably this occurs when build tools scan the environment for dependencies and find them from different distributions.`
So I would advice you to install the stock archlinux instead and try it again. Closing this for now.

**Comment by DarwinUang** [comment]
so… i just reinstalled arch (its plain arch this time) and it works! well, sort of. slim looks pretty good, but when i try to log in, it just returns “Failed to execute login command”
