### ISSUE TITLE
[fvwm] Installation issues

### ISSUE THREAD

**Issue by DylanAkp** [Syndrizzle/hotfiles#40]
Hello, I've done every command in https://github.com/syndrizzle/hotfiles/tree/fvwm
And didn't got any error (fresh install, with git/paru installed before)
Done it in tty without any Desktop Environnement installed

First, I have to login in TTY and then startx
Second issue is what I got :
![20220817_013540](https://user-images.githubusercontent.com/59843812/185003463-e1ac6505-58ff-42f1-a987-7b537b7d5021.jpg)

with no ability to change wallpaper or fix the widget

Some more issues with my installation :
- System menu doesn't open anything
- Bluetooth tile is empty (probably driver-issue, but just in case I write it here)
- There is maybe some useful informations on what's wrong :
![20220817_014823](https://user-images.githubusercontent.com/59843812/185004305-644dea6a-c1e2-4264-af19-54ac64a5381b.jpg)

**Comment by Syndrizzle** [comment]
You can set a wallpaper using nitrogen, please open it, go to Preferences > Add a folder, now select the `.wallapapers` folder, you might want to toggle hidden files if it is not shown, you can do that by pressing <kbd>Ctrl+H</kbd>. Then apply the wallpaper :)
Sorry but I don't know what you mean by the system menu, can you please elaborate a bit more?

**Comment by DylanAkp** [comment]
System menu is the name of an option when rightclicking the desktop, it's also the gear icon on many UI
Seems to be the system settings

**Comment by Syndrizzle** [comment]
Did you install jgmenu?

**Comment by DylanAkp** [comment]
Yes I've installed it.
Finally switched to KDE with some tweaks, but thank you for your help and thank you for your amazing work !

**Comment by Syndrizzle** [comment]
Okay :+1: No problem
