### ISSUE TITLE
Right-click desktop doesn't show icons

### ISSUE THREAD

**Issue by qlAD** [Syndrizzle/hotfiles#41]
Why is there no icon on my desktop when I right click?

**Comment by qlAD** [comment]
Is it because the icon pack is not installed?

**Comment by Syndrizzle** [comment]
Have you moved the /usr directory? If so can you please give me the output of the following command?
```
ls /usr/share/jgmenu
```

**Comment by qlAD** [comment]
> Have you moved the /usr directory? If so can you please give me the output of the following command?
> 
> ```
> ls /usr/share/jgmenu
> ```

**Comment by qlAD** [comment]
> Have you moved the /usr directory? If so can you please give me the output of the following command?
> 
> ```
> ls /usr/share/jgmenu
> ```

Thanks, I found .config/jgmenu in the repository and moved it to my /usr/share/, after that the desktop icons were resolved. However, right-clicking the desktop will not follow the mouse and will only appear in the lower left corner.

**Comment by Syndrizzle** [comment]
What version are you using? The bspwm, fvwm or the worm one?

**Comment by qlAD** [comment]
> What version are you using? The bspwm, fvwm or the worm one?

Bspwm

**Comment by Syndrizzle** [comment]
Ah okay
