### ISSUE TITLE
How can I make the FVWM version work with a 1336x768 screen.

### ISSUE THREAD

**Issue by TalinTheDev** [Syndrizzle/hotfiles#42]
I have just installed arch with no gui. So no gnome or gdm or anything. Before I install this, I would like to know what configuration files I have to edit or at least config options to edit so I know what I'm looking for as I go through the files.

Thanks.

Also, by how much should I edit the values? Like is it a proportion or what?

**Comment by Syndrizzle** [comment]
I don't have a 2nd monitor so I don't know the actual proportion, but you really gotta edit a lot of files, polybar, DPi, fonts, eww, rofi, conky...

**Comment by TalinTheDev** [comment]
OK thanks but it would be a proportion between your width/height and my width/height right?

For eww others too, I have to edit the margins right?

**Comment by Syndrizzle** [comment]
Yeah
