### ISSUE TITLE
Is there a neofetch config folder for the fvwm theme that you posted?

### ISSUE THREAD

**Issue by yikaizhou252** [Syndrizzle/hotfiles#44]
^title
thanks a lot

**Comment by Syndrizzle** [comment]
Ah no, I am not actually using neofetch here, but instead [rxfetch](https://github.com/mangeshrex/rxfetch).
You can find the [script here](https://github.com/Syndrizzle/hotfiles/tree/fvwm/usr/bin/rxfetch):

**Comment by yikaizhou252** [comment]
Oh that makes a lot more sense now. Thanks for the suggestion.
