### ISSUE TITLE
I'm confused as to which manager is used for the bottom navigator and where are its config files

### ISSUE THREAD

**Issue by yikaizhou252** [Syndrizzle/hotfiles#45]
After a bit of struggle, I got everything to sort of work on my display with the exception of the bottom navigator which seems out of place with the rest. Could you let me know the manager that's used for the bottom nav and how to edit it? Thanks a lot!
![image](https://user-images.githubusercontent.com/48587477/185768670-1d7a773a-d35b-482f-8da9-656da8c17353.png)

**Comment by Syndrizzle** [comment]
Ah you can hold down <kbd>ctrl</kbd> and right click on the dock, then select preferences/settings, and change the theme to TokyoNight from the theme selector

**Comment by yikaizhou252** [comment]
that worked!
