### ISSUE TITLE
missing the dock in the buttom

### ISSUE THREAD

**Issue by iErics** [Syndrizzle/hotfiles#46]
My dock is missing, what could be the reason？
![2022-08-22 09 47 42](https://user-images.githubusercontent.com/42070668/185843207-2ba02ab1-9309-4fcf-9fc1-5ded081cb5ab.png)

**Comment by Syndrizzle** [comment]
You need to install plank, and if you have plank installed, please check if there are any errors by running it through command line

**Comment by iErics** [comment]
thank you for your reply，when I run plank, I get this: 
![2022-08-22 20 05 26](https://user-images.githubusercontent.com/42070668/185917511-fafb0aed-788b-4850-84de-06c469fe4834.png)

**Comment by Syndrizzle** [comment]
Are you running the dock from the terminal? Or tty? It cannot detect the Xorg desktop

**Comment by iErics** [comment]
> Are you running the dock from the terminal? Or tty? It cannot detect the Xorg desktop

I run the dock from Kitty. If I execute `sudo plank`,  the dock can launch but cannot change any settings
![2022-08-22 21 34 50](https://user-images.githubusercontent.com/42070668/185934280-7c8f7f24-c051-42ec-aca6-b53fbd4b1db0.png)

**Comment by Syndrizzle** [comment]
You can use `XDG_SESSION_TYPE=x11 plank` to launch plank, without using root, for some reason it doesn't detect your Server, that would fix it, if you want to make it persistent, edit the `+ I Exec plankk &` to `+IExec  XDG_SESSION_TYPE=x11 plank &` in your `~/.fvwm/config` file. Hope that solves it

**Comment by iErics** [comment]
I use the `BSPWM Edition`, so I edit the `plank &` to `XDG_SESSION_TYPE=x11 plank &` in `.config/bspwm/bspwmrc`, it works. thank you so much.
