### ISSUE TITLE
FVWM Installation 

### ISSUE THREAD

**Issue by mrlinuxdude** [Syndrizzle/hotfiles#48]
BUGGED : Installing the dependencies: dont show anything

FVWM  

Installation:
Below are the installation steps to install these dotfiles. Click on a step to expand it.

1. Installing the dependencies:
2. Installing the GTK Theme:
3. Installing the Dotfiles:

**Comment by Syndrizzle** [comment]
Are you on Ubuntu?

**Comment by mrlinuxdude** [comment]
i mean when you click the arrow thingy and its supposed to show you the dependencies, it doesn't.

**Comment by Syndrizzle** [comment]
It only shows them for archlinux, there isn't any guide for ubuntu based distros, as I don't support them

**Comment by mrlinuxdude** [comment]
What do you mean its GitHub DUDE. It should show for ALL. Do you put something special in your code. You might not support them, But other people do and might want to know the dependencies
