### ISSUE TITLE
for some reason the control center doesn't show notification

### ISSUE THREAD

**Issue by Deathemonic** [Syndrizzle/hotfiles#5]
control center doesn't show notification i tested it with notify-send it just wont work even getting a notification it doesn't show up, any clue what's going on?

**Comment by Syndrizzle** [comment]
can u do this and check
So you just go into `~/.config/eww/Control-Center/scripts` and run the logger.zsh file
Can u tell me if there is any error?

**Comment by Deathemonic** [comment]
![screensht_22-06-04_19:02:06](https://user-images.githubusercontent.com/65948476/171996288-59c378d8-685b-4184-b2d6-88819edee060.png)

here's when I run the logger.zsh

**Comment by Syndrizzle** [comment]
That means that the file is working correctly..

**Comment by Syndrizzle** [comment]
Can u try to clear the notifications and then re-send one?

**Comment by Deathemonic** [comment]
![screensht_22-06-05_07:05:25](https://user-images.githubusercontent.com/65948476/172032368-eda4dceb-b619-453f-bea6-733f4b791646.png)

sorry for the weird setup I was using my other hard drive

**Comment by Syndrizzle** [comment]
Well, if you are using my dunstrc, then all you need to do is just press the clear all button (the one to the right of Notifications), if you are not using my dunstrc, then u need to append 3 lines to yours so that it executes the script everytime a new notification is received. 
```
[logger]
summary = "*"
script = "~/.config/eww/Control-Center/scripts/logger.zsh"
```
Then press the clear all button and try to send a notification 😄

**Comment by Deathemonic** [comment]
Oh that's why, ok Ill try if this works

**Comment by Deathemonic** [comment]
sorry for the long reply, I tried it but it still won't work but checking the logs it seems the it doesn't recognize scroll as a widget for some reason
![Screenshot_2022-06-05-10-43-45_1280x800](https://user-images.githubusercontent.com/65948476/173024770-c25d101c-107d-4e21-8f7f-278f206f13a9.png)
![Screenshot_2022-06-10-04-25-54_1280x800](https://user-images.githubusercontent.com/65948476/173024796-927b0eda-409b-4747-83fd-4d89efbbef71.png)

**Comment by Deathemonic** [comment]
I'll try doing some test if there's something missing, the script works it's just eww

**Comment by Deathemonic** [comment]
just figured it out that im using a old version of eww

**Comment by Syndrizzle** [comment]
Oh, I guess upgrading it might do it

**Comment by Deathemonic** [comment]
lol thanks for the help, you can close this issue

**Comment by Syndrizzle** [comment]
Sure :)
