### ISSUE TITLE
FVWM sound bar 

### ISSUE THREAD

**Issue by ValgulNecron** [Syndrizzle/hotfiles#50]
so there is two sound control the first on the bottom bar and the panel the first problem is that both of one are not "linked" editing one do nothing to the second
and changing the value do nothing

**Comment by Syndrizzle** [comment]
Hello! Can you please specify a bit more about the issue?

**Comment by Syndrizzle** [comment]
The battery won’t work on a vm, try to install these
`sudo pacman -S alsa-utils pamixer` Try that and see if it fixes the problem.

**Comment by ValgulNecron** [comment]
installing alsa-utils fixed the issue i searched why it was not installed with the arch instruction but it's not in the package installed in any step
