### ISSUE TITLE
[bspwm] some bug with eww??

### ISSUE THREAD

**Issue by MrIvanPlays** [Syndrizzle/hotfiles#51]
when i click for example the shutdown button the whole screen blacks out and only that window is shown. animations also bug. happens after some time after the computer is turned on. 

**MISC**: the only modifications i applied were about my second screen to turn on and also have a polybar there. that's basically it.

**Comment by Syndrizzle** [comment]
Try to disable the animations
`sudo pacman -S picom` to install the normal picom
For the shutdown thing, can you try to shutdown from the terminal to see if that works?

**Comment by MrIvanPlays** [comment]
all the ui elements are working kinda properly. problem showcase: 
![image](https://user-images.githubusercontent.com/37958105/196206864-9d086fa1-6a3d-4521-8cc8-d9491e2b4cae.png)
also there is a issue with the showcased menu: when i click on stuff it works but the ui elements don't update their visuals. (i should probably modify it after it gets fixed to remove some stuff and change some icons because this is a pc instance and not a laptop)

the screen shouldn't be black when i open this window should it be

**Comment by Syndrizzle** [comment]
The screen goes black because you aren't running any compositor. Also, please install all the dependencies, it seems like some of them are missing. 
`bluez` is required for the Bluetooth to work.
`rfkill` for airplane mode. 
`wireless-tools` for the Wi-Fi to work 
`redshift` for the night light to work, that's the reason the buttons do nothing.

**Comment by MrIvanPlays** [comment]
The pc doesn't have a wifi module nor a bluetooth one. I modified the wifi module in the polybar so it shows up for my ethernet cable. That's why i removed such packages. Also idk whats about the compositor, what shall i add into the bspwmrc so it works.

**Comment by MrIvanPlays** [comment]
I've manually ran picom and it is full of errors
![image](https://user-images.githubusercontent.com/37958105/196421521-5077cfd3-4bb6-42de-98ee-0fed0de11ea4.png)

perhaps it crashes when it is ran by the bspwmrc?

**Comment by MrIvanPlays** [comment]
also i've explicitly enabled compositing in the x server config via:

```
Section "Extensions"
    Option "Composite" "Enable"
EndSection
```
but it still doesn't fix it.

**Comment by Syndrizzle** [comment]
You can ignore those errors, happens to me as well. Is the compositor running regardless?

**Comment by MrIvanPlays** [comment]
Says its running

**Comment by MrIvanPlays** [comment]
looks like picom crashes/stops working for some weird reason because of this:
![image](https://user-images.githubusercontent.com/37958105/196448490-9e362603-bcf1-4aa3-9b33-80b14da68370.png)

before doing any change to this everything worked fine except again the eww windows: they were opening correctly, but no data was correct about them. for example the spotify player didn't display any information whatsoever

**Comment by MrIvanPlays** [comment]
update: the spotify window issue has resolved itself. but there's still a problem with these 2:

![image](https://user-images.githubusercontent.com/37958105/196689051-3f023fc3-60e8-4b9c-8fca-56e429a50074.png)

![image](https://user-images.githubusercontent.com/37958105/196689087-4fc35b05-eae0-4f57-aeb2-91632f3c7b95.png)

they're not working at all properly.

**Comment by Syndrizzle** [comment]
What is your distro?

**Comment by Syndrizzle** [comment]
Can you share me eww logs?
`killall eww`
`eww daemon`
`eww logs`

Then open any widget and see any red things popping up

**Comment by MrIvanPlays** [comment]
![image](https://user-images.githubusercontent.com/37958105/197387301-a1ef68df-d5f7-42db-9e62-6b26d8258010.png)

**Comment by Syndrizzle** [comment]
It seems like everything is fine, I am not sure if your dual monitor is causing the problem

**Comment by MrIvanPlays** [comment]
I literally did no modifications to eww whatsoever. For my 2nd monitor the only modification i did was to create a polybar with it showing the time and the layout change button.

**Comment by MrIvanPlays** [comment]
update: looks like eww bugs only when I open that window: 
![image](https://user-images.githubusercontent.com/37958105/198106183-a910064b-f94d-4876-a1f9-69aabe1184f5.png)

if I click on the spotify window before I open this one everything works as expected.

**Comment by Syndrizzle** [comment]
I think the scripts are acting weird because of missing dependencies
