### ISSUE TITLE
eww conflicting variables

### ISSUE THREAD

**Issue by M-Manas-s** [Syndrizzle/hotfiles#52]
Hi, thank you for the super awesome rice. The eww daemon wasn't working from right after installation. I dug into the issue a bit and found this. There are conflicts among the eww variables -

`volume`
`brightness`

 in the files -

`.config/eww/System-Menu/eww.yuck` - lines 29 and 31
`.config/eww/Main/eww.yuck` - lines  14 and 15

![2022-11-21_22-00](https://user-images.githubusercontent.com/46261625/203111059-673657a6-f5e1-4114-8702-d708deba74fd.png)

I commented those in the /System-Menu/eww.yuck file and everything seems to be working then. The volume is getting polled from the system rather than the slider which does the job too. 

I didn't modify anything after installing and this wasn't working for me. I'm sorry if there was a bug/mistake on my part but after this change everything went back to normal. Tell me if you require additional logs/tests/statistics. Thank you again.

**Comment by Syndrizzle** [comment]
Thank you for the issue! I'll look into this :)
