### ISSUE TITLE
How can i put spotify in window mode? and how can i configure this?

### ISSUE THREAD

**Issue by JefHern** [Syndrizzle/hotfiles#53]
![image](https://user-images.githubusercontent.com/109345723/205977445-20bf3ff8-095f-417d-b2c1-27f3bdd21f2a.png)

I dont really care so much about the spotify "issue" but I was searching for hours how to edit that... Sry for open a issue post´
[EDIT] - I solved the part of edit the conky but now i have anoher one, where is the file where i can config the pointer? (I still having the spotify "issue")

**Comment by Syndrizzle** [comment]
Spotify is a pain for window managers, but it should be floating already since I have already set it up. :thinking: 
https://github.com/Syndrizzle/hotfiles/blob/bspwm/.config/bspwm/scripts/external-rules

I don't know what do you mean by the pointer thing, can you please explain me if possible?

**Comment by Syndrizzle** [comment]
Maybe you can try this:
https://github.com/dasJ/spotifywm

For cursor, you can change it to your desired one by editing ~/.Xresources file and changing the cursor theme name

**Comment by JefHern** [comment]
Where do I have to put my path LD_PRELOAD=/path/to/spotifywm.so /path/to/spotify/binary in the code? And where can I see the available themes for the pointer? Do I have to install something? sorry for so many questions

**Comment by Syndrizzle** [comment]
You need to put it in your spotify .desktop file, in `/usr/share/applications/spotify.desktop`, and you will need to make it so it points to the install spotifywm.so file before the spotify path.
For cursor theme, you will need `lxappearance`.
