### ISSUE TITLE
will you make dependencies install command for debian based distro?

### ISSUE THREAD

**Issue by lebakhai13** [Syndrizzle/hotfiles#54]
please add dependencies install command for debian based distro user

**Comment by Syndrizzle** [comment]
I don't currently support debian, Sorry, because it has some difference in the internal working when compared to arch, like it uses `dash` instead of `sh`, which breaks some scripts, it cannot handle PPAs, so some software is missing....

**Comment by lebakhai13** [comment]
> 
thank you for answer, i wanna in the future you can make hotfiles for debian based
