### ISSUE TITLE
Missing navigation bar (bspwm)

### ISSUE THREAD

**Issue by JcefEmbed** [Syndrizzle/hotfiles#55]
Navigation bar plain does not exist and elements such as the power button cannot be clicked. I have verified that I have plank and jgmenu installed.

**Comment by Syndrizzle** [comment]
The navigation bar is polybar, Make sure you got that one, try to run it from the terminal to see if it is not erroring our. Also you cannot click the power button because i think you are not having the eww widgets installed.
Also, what's your screen resolution

**Comment by JcefEmbed** [comment]
Fixed, was missing eww-widgets.
Once again thank you for the awesome dotfiles.

**Comment by Syndrizzle** [comment]
No problem :)
