### ISSUE TITLE
even weirder issue

### ISSUE THREAD

**Issue by DarwinUang** [Syndrizzle/hotfiles#9]
copypasted from #4 because i’m pretty sure no one reads it anymore

so… i just reinstalled arch (its plain arch this time) and it works! well, sort of.

when i start slim (yeah i start slim with systemctl lol), it looks pretty good, but when i try to log in, it just returns “Failed to execute login command”

**Comment by Syndrizzle** [comment]
Ok a fix for this would be, you need to edit `/etc/slim.conf` file and uncomment the session_dir line

Then replace your .xinitrc with this one:
```
#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
exec $1
```
**Make sure you only have worm installed as your de/wm, before doing this remove any desktop environment or window manager other than worm or slim will act weird**

**Comment by DarwinUang** [comment]
now, after "successfully" logging in, worm instantly crashes and restarts.

**Comment by Syndrizzle** [comment]
Ok how about
```
#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec worm 
```
sorry i was busy with life so i couldn't reply on time :/

**Comment by DarwinUang** [comment]
sorry for the late reply

so...

- uncommented `session_dir` in `/etc/slim.conf`
- replaced `exec $1` with `exec worm` in `~/.xinitrc`

now, instead of crashing, slim just freezes.

pam says something about a "daemon control file", if that helps

**Comment by Syndrizzle** [comment]
are you using PAM?

**Comment by DarwinUang** [comment]
> are you using PAM?

the `pam` package is a dependency of the `base` meta-package (which you should install, if you havent already!) so yeah i use pam

**Comment by Syndrizzle** [comment]
I don't use pan, so I don't have any idea about the issue you are having, and also I think you should try to do it without PAM to see if it works

**Comment by DarwinUang** [comment]
i can't just remove pam...

**Comment by Syndrizzle** [comment]
Can you try to use any other dm rather than slim? see if it works

**Comment by DarwinUang** [comment]
tried out lightdm, didnt work

**Comment by Syndrizzle** [comment]
I cant seem to reproduce your issue :/
